version: '2'

services:
    db:
        image: mariadb:latest
        volumes:
            - "../data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: wiseflow
            MYSQL_USER: wiseflow
            MYSQL_PASSWORD: test
        ports:
            - 3306:3306
    php:
        build: php-fpm
        image: test-php:latest
        environment:
            SERVER_ENVIRONMENT: "local"
            DATABASE_URL: "mysql://wiseflow:test@db/wiseflow"
        volumes:
          - ./app:/app/
    nginx:
        build: 
            context: .
            dockerfile: nginx/Dockerfile
        image: test-nginx:latest
        ports:
            - 80:80
